apiVersion: v2
name: entitlements
version: 0.0.1
description: A deployed service to configure entity/attribute mappings in an openTDF ABAC system
type: application
maintainers:
  - name: Virtru
icon: https://inxmad4bw31barrx17wec71c-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/o_efa1e48d0db5ebc8-4.png
appVersion: "0.0.1"
