eas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: abacus.etheria.local
      paths:
      - /eas
    tls:
    - hosts:
      - abacus.etheria.local
      secretName: eas-tls
  endpoints:
    kasDefaultUrl: https://abacus.etheria.local/kas
  image:
    name: opentdf/entity-attribute-service:virtrulocal
    pullPolicy: Never
  service:
    type: ClusterIP

kas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: abacus.etheria.local
      paths:
      - /kas
    tls:
    - hosts:
      - abacus.etheria.local
      secretName: kas-tls
  endpoints:
    easHost: https://abacus.etheria.local/eas
  image:
    name: opentdf/kas:virtrulocal
    pullPolicy: Never

attribute-provider:
  image:
    name: opentdf/claim-test-webservice:virtrulocal
    pullPolicy: Never
  port: 5000

keycloak-bootstrap:
  image:
    name: opentdf/keycloak-bootstrap:virtrulocal
    pullPolicy: Never

attributes:
  image:
    name: opentdf/attributes:virtrulocal
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    user: postgres
    schema: tdf_attribute

entitlements:
  image:
    name: entitlements:virtrulocal
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    database: tdf_database
    schema: tdf_entitlement

tdf-storage:
  image:
    name: opentdf/storage:virtrulocal
    pullPolicy: Never
  s3Bucket: "datalake.etheria"
  s3BucketRegion: "us-west-2"
