endpoints:
  easHost: https://abacus.etheria.local/eas
replicaCount: 1
service:
  type: ClusterIP

# Development image for minikube - for nonlocal envs, override this with a proper version
# This should be preloaded into minikube by a local setup script
image:
  name: tdf3.service.kas:virtrulocal
  pullPolicy: Never

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: abacus.etheria.local
    paths:
    - backend:
        service:
          name: kas
          port: 8000
      path: /kas
  tls:
  - hosts:
    - abacus.etheria.local
    secretName: kas-tls

livenessProbe: null
readinessProbe: null
