{{- if .Values.ingress.enabled -}}
{{- $fullName := include "storage.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "storage.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  rules:
    {{- range $host, $paths := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range $path, $backend := $paths }}
          - path: {{ $path }}
            pathType: {{ $backend.pathType | default "ImplementationSpecific" | quote }}
            backend:
              service:
                name: {{ $backend.serviceName | default $fullName | quote }}
                port:
                  number: !!int {{ $backend.servicePort | default $servicePort }}
          {{- end }}
    {{- end }}
{{- end }}
