kas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
      abacus.opentdf.local:
        "/kas": {}
    tls:
      - hosts:
          - abacus.opentdf.local
        secretName: kas-tls
  endpoints:
    easHost: https://abacus.opentdf.local/eas
  image:
    name: opentdf/kas:head
    pullPolicy: Never

attribute-provider:
  image:
    name: opentdf/claim-test-webservice:head
    pullPolicy: Never
  port: 5000

keycloak-bootstrap:
  image:
    name: opentdf/keycloak-bootstrap:head
    pullPolicy: Never

attributes:
  image:
    name: opentdf/attributes:head
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    user: postgres
    schema: tdf_attribute

entitlements:
  image:
    name: opentdf/entitlements:head
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    database: tdf_database
    schema: tdf_entitlement

tdf-storage:
  image:
    name: opentdf/storage:head
    pullPolicy: Never
  s3Bucket: "datalake.opentdf"
  s3BucketRegion: "us-west-2"
