affinity: {}
autoscaling:
  enabled: true
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: virtru/tdf-abacus-web
imagePullSecrets: []
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
  enabled: true
  hosts:
  - host: abacus.example.com
    paths:
    - backend:
        service:
          name: abacus
          port: 443
      path: /(.*)
    - backend:
        service:
          name: eas
          port: 4010
      path: /eas/(.*)
    - backend:
        service:
          name: kas
          port: 8000
      path: /kas/(.*)
  tls:
  - hosts:
    - abacus.example.com
    secretName: abacus-tls
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 3
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
securityContext: {}
service:
  port: 443
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []

# Pod disruption budget
maxUnavailable: 1

endpoints:
  eas: https://eas.example.com/
  kas: https://kas.example.com/
  abacus: https://abacus.example.com
  nginxHost: abacus.example.com
