apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "claims.name" . }}-cm
data:
  POSTGRES_DATABASE: {{ .Values.postgres.database }}
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  SERVER_LOG_LEVEL: {{ .Values.logLevel }}
