apiVersion: v2
name: claims
version: 0.0.1
description: Provides 'claims' objects as the backend for an openTDF authZ service
type: application
maintainers:
  - name: Virtru
icon: https://inxmad4bw31barrx17wec71c-wpengine.netdna-ssl.com/wp-content/uploads/2018/12/o_efa1e48d0db5ebc8-4.png
appVersion: "0.1.0"
