fullnameOverride: keycloak
image:
  # Keycloak is a non-OpenTDF chart, but with an OpenTDF image
  repository: ghcr.io/opentdf/keycloak
  tag: 21.1.2-1.6.0
postgresql:
  # This next option (enabled) determines whether Keycloak should
  # create a Postgres (uniquely) for Keycloak (true) or not (false).
  #
  # Since it's set to false, we'll use the Postgres provided by OpenTDF
  enabled: false
command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start-dev"
externalDatabase:
  database: keycloak_database
extraEnv: |-
  - name: CLAIMS_URL
    value: http://entitlement-pdp:3355/entitlements
  - name: JAVA_OPTS_APPEND
    value: -Djgroups.dns.query=keycloak-headless
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_PORT
    value: "5432"
  - name: KC_LOG_LEVEL
    value: INFO
  - name: KC_HOSTNAME_ADMIN
    value: "localhost:65432"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HOSTNAME_STRICT_BACKCHANNEL
    value: "false"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_URL
    value: "http://localhost:65432/auth"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"
  - name: KC_PROXY
    value: "edge"
extraEnvFrom: |-
  - secretRef:
      name: "keycloak-secrets"
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /auth/$2
  rules:
    - host: localhost
      paths: &paths
        - path: /auth(/|$)(.*)
          pathType: Prefix
    - host: opentdf.local
      paths: *paths
    - host: offline.demo.internal
      paths: *paths
  tls: []
