image:
#  ghcr.io == GitHub packages
  registry: docker.io
  repository: opentdf/keycloak
  tag: head
  pullPolicy: Never
imagePullSecrets:
  - name: virtru-regcred
auth:
  createAdminUser: true
  adminUser: keycloakadmin
  adminPassword: mykeycloakpassword
postgresql:
  enabled: false
externalDatabase:
  host: opentdf-postgresql
  user: postgres
  password: mydbapassword
  database: keycloak_database
extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: KEYCLOAK_USER
    value: keycloakadmin
  - name: KEYCLOAK_PASSWORD
    value: mykeycloakpassword
  - name: CLAIMS_URL
    value: http://opentdf-claims:5000/v1/claims
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "http://localhost:65432/keycloak/auth"
  - name: KEYCLOAK_EXTRA_ARGS
    value: >-
        -Dkeycloak.frontendUrl=http://localhost:65432/keycloak/auth
        -Dkeycloak.adminUrl=http://localhost:65432/keycloak/auth
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /keycloak(/|$)(.*)
  hostname: localhost
  extraHosts:
    - name: host.docker.internal 
      path: /keycloak(/|$)(.*)
      pathType: Prefix
