name: Vulnerability Tests
on:
  push:
    branches: [ main, feature/init ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |-
        cd vulnerability
        npm ci
    - name: Install Playwright
      run: |-
        cd vulnerability
        npx playwright install --with-deps
    - name: Run Playwright tests
      run: |-
        cd vulnerability
        npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-test-results
        path: vulnerability/test-results/
